spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ...
    username: ...
    password: ...

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
   error:
     include-stacktrace: never        
